// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMMbhBzlw5ieWskQcx7hm5FEAR7Xo9Mn4',
    appId: '1:217376248703:web:f049bf89ec48dd445e004a',
    messagingSenderId: '217376248703',
    projectId: 'flutterudemyapphackathon',
    authDomain: 'flutterudemyapphackathon.firebaseapp.com',
    storageBucket: 'flutterudemyapphackathon.appspot.com',
    measurementId: 'G-E88VF6SNXC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjm_z7gyA1GvfDFXu0ZJvR-p-QMkjKT9Y',
    appId: '1:217376248703:android:332ccd610ecb08d35e004a',
    messagingSenderId: '217376248703',
    projectId: 'flutterudemyapphackathon',
    storageBucket: 'flutterudemyapphackathon.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1xpko874eFNi3_Og2YoD2tZmao8RP9ps',
    appId: '1:217376248703:ios:dab47c54b5d0f1075e004a',
    messagingSenderId: '217376248703',
    projectId: 'flutterudemyapphackathon',
    storageBucket: 'flutterudemyapphackathon.appspot.com',
    iosClientId: '217376248703-ev3pcvpkemh0rs9a6bdne07i7iohd25v.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1xpko874eFNi3_Og2YoD2tZmao8RP9ps',
    appId: '1:217376248703:ios:dab47c54b5d0f1075e004a',
    messagingSenderId: '217376248703',
    projectId: 'flutterudemyapphackathon',
    storageBucket: 'flutterudemyapphackathon.appspot.com',
    iosClientId: '217376248703-ev3pcvpkemh0rs9a6bdne07i7iohd25v.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );
}
